name: Train on EC2

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Train via SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters commands='[
              "docker pull ${{ secrets.ECR_REPOSITORY_URL }}/${{ env.PROJECT_ID }}:latest",
              "docker run -d \
                -e MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }} \
                --network host \
                --name app \
                ${{ secrets.ECR_REPOSITORY_URL }}/${{ env.PROJECT_ID }}:latest"
            ]' \
            --comment "Run training container" \
            --output text